### ISSUE TITLE
Core features

### ISSUE THREAD

**Issue by howardchung** [howardc93/dukeexchange#1]
- [x] Logging in through Facebook or Google (and possibly an option of manual log in/sign up)
- [x] When listing an item, sellers fill out fields regarding size, condition, brand, color, etc. Eventually these could be drop-down lists or autofill so that sellers don't have to enter everything manually
- [ ] Selling system: sellers post an 'asking price' and buyers can message them with offers. When an offer is accepted, contact details are exchanged. Later we could add a bidding/auction feature
- [ ] Home-page could be a Pinterest-like feed of images of listed items?
- [ ] Buyers can browse for items by clicking through categories or typing terms into a search box.  After clicking into a category, buyers can refine the listings furthermore through filters such as condition, price, size, etc.

Just a quick listing of features, feel free to make sub-issues for each of these so we can close them as we work.

**Comment by howardchung** [comment]
I didn't know you could do checkboxes.  That's pretty awesome :)

**Comment by themichaellai** [comment]
github so [fancy](https://www.youtube.com/watch?v=O-zpOMYRi0w)

**Comment by howardchung** [comment]
separated out into sub-issues
