### ISSUE TITLE
Sending an email when an offer is made

### ISSUE THREAD

**Issue by themichaellai** [howardc93/dukeexchange#10]
This could be done by either
- Using something like [nodemailer](https://github.com/andris9/Nodemailer)
  - _This is the ideal case_
  - However, there might be potential to be sent directly to spam? Would have to investigate to see if this is an issue.
- Using something like [sendgrid](https://sendgrid.com/)
  - Costs money, but should be fine for mvp with their free plan, and we have a little runway money.
- Using a `mailto:` link
  - Not ideal, exposes the seller's email address. Ideally the buyer's email is included in the email, and the seller can decide whether to sell it to them or not.

**Comment by themichaellai** [comment]
@howardc93 decided to go with sendgrid, I can give you my credentials for testing if you don't have any you can use.

**Comment by howardchung** [comment]
Okay
