### ISSUE TITLE
Offers

### ISSUE THREAD

**Issue by themichaellai** [howardc93/dukeexchange#3]
People should be able to privately make an offer for a listing.

Each listing has an 'asking price' and buyers can make an offer on the item.  The user who listed the item can view all offers that were made.  

When an offer is accepted:
Each listing also includes the email address of the person who offered.  It's up to the buyer to set up a meeting via email or other medium.
The listing becomes "closed" and offers can no longer be made on it.

**Comment by howardchung** [comment]
@themichaellai 

Originally I planned to store offers intheir own collection.  Each offer would then have a listing_id and user_id.  However, MongoDB doesnt have JOIN like SQL does, so when displaying the offers, each user has to be looked up again and the email filled at display time.

What do you think about denormalizing the data and storing offers as an array within each listing?  We would then put the email and user_id at insertion time, and would not require any more lookups at display time.

**Comment by themichaellai** [comment]
Yeah, was about to ask you about this -- I think it makes sense to put the offers inside of the listing document, since I don't believe a specific offer will be shown outside of the context of a listing, right?

As far as for the user information inside of the offer, I'm not sure whether putting the user inside the offer would be beneficial or not. When displaying an offer, it would be really nice to see the name of the user, but I think that adds a lot of complexity into updating user info. Perhaps we can create a JSON endpoint, and then load in the user information with javascript? That's also kind of messy. The alternative would be doing a synchronous lookup of the user information from the userIds after the listing is retrieved, which would appear slower to the user but reduces complexity.

**Comment by themichaellai** [comment]
Also, it might be worth thinking about sending emails to a listing owner when an offer has been made. It's probably not a large priority for the mvp, but if we can use something like mailchimp or sendgrid (since we have some dough now) then it might be easy to drop in.

**Comment by howardchung** [comment]
I don't particularly like the "hybrid" approach of storing offers within listings but not the full data.  We should either store offers in a separate collection and do the "synchronous" lookup (psuedo-join), or we should store the full data we need for an offer inside the listing and avoid the lookups completely.

If we denormalize the data, so we end up duplicating it within the offer.  Since we're denormalizing, we can choose what fields we want to insert at the time the offer is made.  It would be user_id and email at minimum.  Adding name would not be difficult.

One thing to note is that if the user's name/email change, the offer will not reflect this update since it's stored as a copy within the listing.  This probably isn't a major concern in most cases.

Re: email, I have used SendGrid in the past with https://github.com/howardc93/foodpoints
They allow 400 free emails a day.

**Comment by howardchung** [comment]
I'm going with separate collection+lookups.  It should scale okay since the number of offers per listing should not scale with userbase (at least not linearly)

**Comment by themichaellai** [comment]
~~I was proposing we store the entire offer inside of the listing, sorry if that wasn't clear.~~ OK -- separate seems reasonable as well.

And :+1:  on embedding users' email/userId/name in the offer. If updating names ever becomes an issue, we can just run a job to update names every x minutes...

**Comment by howardchung** [comment]
I prefer to avoid running scheduled jobs whenever possible :)

**Comment by howardchung** [comment]
Still needs styling though, I am dumping the current as JSON:

User page: List of offers the user has made, joined with the listing name.

Listing page: List of offers made on this listing (only visible to the listing owner)

**Comment by themichaellai** [comment]
Would it be possible to add a message field to offers?

**Comment by howardchung** [comment]
Yeah, should be easy.  Do you want me to do it?

**Comment by themichaellai** [comment]
Yeah that'd be great, thanks.

**Comment by howardchung** [comment]
After playing around with webpack--it seems like it will take care of
watching and minifying already?  Do we need to use gulp on top of that?

**Comment by themichaellai** [comment]
Yeah -- I've set it to use webpack's watcher, but I'm not using their minifier, which I guess I should have used. 

Webpack also handles stylesheets, but using gulp on top of it because it seems it would be less awkward. If we have a page that doesn't use javascript, I think we'd have to have a JS file for the page anyways in order to "require" the stylesheets. I could be wrong, so I'll take another look again.

**Comment by themichaellai** [comment]
hey -- were you working on the frontend for this?

**Comment by howardchung** [comment]
I haven't done any work toward displaying, so you could do that if you want
something to work on.

**Comment by themichaellai** [comment]
Do you mind just doing something really basic where it shows the offers with their messages and the emails, and just show it to the listing owner?

**Comment by howardchung** [comment]
Done.  Could probably be prettied up a bit, but that can be done later
