### ISSUE TITLE
Browsing interface

### ISSUE THREAD

**Issue by themichaellai** [howardc93/dukeexchange#5]
There should be an interface that allows people to filter all items by attributes of listings.

Buyers can browse for items by clicking through categories or typing terms into a search box. After clicking into a category, buyers can refine the listings furthermore through filters such as condition, price, size, etc.

**Comment by themichaellai** [comment]
Going to try for just the browsing interface, search can be sugar because it's likely the browsing interface will be enough to filter through things.

@howardc93 Do you know a good way to do search? I don't think there's a nice way to do it in mongo...?

**Comment by howardchung** [comment]
There's this:
http://docs.mongodb.org/manual/reference/operator/query/text/

Or you can bring it something like elasticsearch, which is likely more performant.
