### ISSUE TITLE
implement support for multiple images

### ISSUE THREAD

**Issue by howardchung** [howardc93/dukeexchange#6]
implementation plan:
each listing document contains a key that maps to an array of base64 strings.  Each string is an encoding of an image.  If there is only one image, it is an array of one string.

Currently we store the string directly, and so only support one image per listing.

**Comment by howardchung** [comment]
Migration plan: If we decide to move to s3 or some other system that's better designed for image hosting it should be possible to export all the images from MongoDB.

**Comment by themichaellai** [comment]
Not sure if we talked about this, but could we just use a colab vm? I don't think I'm using mine for anything at the moment. That might also solve other problems as well.

**Comment by howardchung** [comment]
Sure, we could.  I use mine for development so if we want to optimize performance we can host it on yours.  We'll lose the use of those on graduation, though, so we need a migration plan out.

**Comment by themichaellai** [comment]
Sure, so I'll go ahead and roll back the base64 strings and start using image files?

**Comment by howardchung** [comment]
Yeah, I guess you can store the uploaded file name in the db and we can define a constant for the file path.  You're still going to need to support multiple images though, so it has to be an array of file names?

**Comment by themichaellai** [comment]
Yeah, that's the plan, unless the images need to represent something symbolical, like I mentioned in an email (different perspectives).

**Comment by howardchung** [comment]
You mean the user attaches metadata to the image saying "front","back", etc?  I don't think that's necessary, the listing can just contain a "gallery" of images and the viewer can scroll through them.

**Comment by themichaellai** [comment]
I was saying that other sites attach a symbolic meaning to images, so I wasn't sure if we should do that as well. I think this is something we should ask about.

**Comment by howardchung** [comment]
Could you explain what you mean by "symbolic meaning"?  I can't find the email

**Comment by themichaellai** [comment]
Like a user would need to supply an image of the front of the item, back of the item, an image of any defects, and/or an image of the item being worn. (Was the last email I sent Mar 13)

**Comment by howardchung** [comment]
Yeah, I don't think that will be necessary (at least not to specify that a specific image is from a specific perspective).  They could provide all of those perspectives if they like and we just show the array of images in the listing.  We can ask Meaghan about it if you like.

**Comment by themichaellai** [comment]
True, I think that's the best solution but we should probably ask to make sure.

**Comment by howardchung** [comment]
implemented and tested?  have we checked for corner cases (no images, too many images?)

**Comment by themichaellai** [comment]
I tested [no images](https://github.com/howardc93/dukeexchange/blob/1c2febef10bc08d2001386056232887b420f49f7/public/js/imageupload.js#L19), haven't tested too many images yet, but will. Is four images a reasonable limit on the number of images?

I also haven't finished the styling of the form, there's some cruft from the library I'm using.

**Comment by howardchung** [comment]
Yeah, it's just a configurable option (to set a max), right?

**Comment by themichaellai** [comment]
Yeah it is, but it would be good to check for any weirdness and enforce some checking on the server side.
